### PR TITLE
Native routing proposal - how could we solve routing without external solution

### LINKED ISSUE #14: Replace router with Slim-Router
The current router is very static and should be replaced with the router from the slim framework.

Similarly like in the [simple-webshop repo](https://github.com/tolik518/simple_webshop/blob/master/code/src/Router.php).

### PR DESCRIPTION
**Pull request by pavelee**
Hey,

It's related to the issue #14 

I have prepared a proposal how could we solve the router issue with native solution, without using external library from the slim framework.

I did that because as i understand the project exists in learning purpose at first. Of course problem is solved at every ready to go framework, but implementing it yourself is great exercise for software architecture skills.

What i did:

1. What is already great in your project is existing interface Page. That is crucial because relay on abstraction is the key for good software. So i extended this interface with extra few methods:

```php
<?php

namespace Returnnull;

interface Page
{
    // edited interface, now run has input (Request) and output (Response).
    public function run(Request $request): Response;

    // new method, each page should return what url it supports.
    // It's array of regexes. Regexes becouse it's flexible and powerful. Array to allow decomposing complex regexes to smaller ones.
    public function getSupportedUrlRegexes(): array;

    // new method, each page can answer that can support Request or not.
    // here you can check path, method, headers, etc.
    public function isUrlSupported(Request $request): bool;

    // new method, each page can answer that can support Request or not.
    // right now if page is protected, it will be called only if user is logged in.
    public function isProtected(): bool;
}
```

2. Now Router load all pages from Page folder and looking for supporting one. It's cool because it allows to follow Open/Close principle. There is no need to modify Router. There is one exception, if router doesn't find any supporting page it will always return PageNotFoundPage. 

3. New Page Factory. Now you just delegate creating page to specialize Object with this responsibility. What gives us is much cleaner Router dependecines. Now you don't need to pass each route, you just pass Factory 🥳 (again Open/Close principle)

```php
    private function createRouter(): Router
    {
        return new Router(
            new PageFactory(
                $this->mySQLConnector
            ),
            new FileSystem(),
            new VariablesWrapper(),
            new SessionManager()
        );
    }
```

4. Request and Response Objects to make router much more cleaner. Now you always get Request object as input, and we expect Response as result. You don't need any more do echo in your pages. Now Application will handle that for you. So our process looks very simple:

```php
    public function run(): void
    {
        $this->tracker->trackUserInfo();
        $this->page->run(Request::getInstance())->send(); // just do the job!
    }
```

5. Adding new page now it's just adding new extra class to Pages folder. For example you can define new file TestPage:

/blog.returnnull.de/code/src/Pages/TestPage.php

```
<?php

namespace Returnnull;

class TestPage extends BasePage
{
    public function run(Request $request): Response
    {
        return new Response('Hello world!');
    }

    public function getSupportedUrlRegexes(): array
    {
        return ['/test/'];
    }
}
```

Now go to http://localhost/test and it's just works! 🥳

It works so easily because it doesn't have any dependecines. If that would be the case you have to define initialization in PageFactory class. We don't have dependency injection feature, but who nows maybe we will do that as well! 😁

It's just proposal, so don't feel any pressure to the solution. If you like it or would like to change something, go ahead! 🙏

### CODE REVIEW

**Comment by pavelee** [comment]
ah, forget about BasePage class, it's just optional class between Page interface and concrete pages. It allows to minimize DRY.

For example method isUrlSupported is now pretty the same for all pages. 

```php
    public function isUrlSupported(Request $request): bool
    {
        foreach ($this->getSupportedUrlRegexes() as $regex) {
            if (preg_match($regex, $request->getUri())) {
                return true;
            }
        }
        return false;
    }
```

What important, you still can overwrite method in concrete Page, so there is no flexibility cost! 😁

**Comment by tolik518** [comment]
Hey @pavelee, thank you very much for the proposal.
I'll go over it in detail some days in the future :)

Would you like me to do a code review so you can apply the changes on your own - or do you prefer me to commit the changes directly to your branch?

**Comment by pavelee** [comment]
Thank you!

Commit directly into the branch 🙏

**Comment by tolik518** [comment]
Thanks a lot for the PR - I had a lot of fun reviewing and testing it. Your changes added great value! :)

I made some minor adjustments, while the biggest adjustment was removing the BasePage in the spirit of "Composition over inheritance". The Page Interface that you extended is just enough for our case. 
Furthermore, I tried to make some of the methods smaller and introduced early returns to some methods.

For the smaller changes, you can just look over the commits I made. 

If you are okay with the current state, I would merge the PR.

**Comment by pavelee** [comment]
Sorry for the mysql image change 🫣😣

Thank you for the review! 🙏 i will take a look and will be back with feedback!

**Comment by tolik518** [comment]
No worries, I saw that you changed the Dockerfile, but instantly forgot once I pulled the changes 😅

**Comment by pavelee** [comment]
Code looks fine! 🥳

I did two small adjustments:

- In FileManager i fixed extension filter, because i didn't work as it should (probably that why you removed it). Now it should be fine, it's worth to keep it.
- small exception message fix 

If it is fine, i think it is ready to merge! 🚀

**Comment by pavelee** [comment]
btw, cool 404 page! 😄

**Pull request merged**
